import { ItemDef, ItemId, CraftingRecipe, CodexEntry } from '../types/game';

export const ITEMS: Record<ItemId, ItemDef> = {
  // Raw Botanical Byproducts
  resin_sap: {
    id: 'resin_sap',
    name: 'Resin Sap',
    category: 'raw',
    description: 'Thick, sticky sap from Sap-Weavers. Essential adhesive for organic bio-composite structures.',
    iconName: 'Droplet',
    color: '#f59e0b',
    rarity: 'common',
    maxStack: 99,
  },
  vibrant_petal: {
    id: 'vibrant_petal',
    name: 'Vibrant Petals',
    category: 'raw',
    description: 'Iridescent flower petals from Petal-Mills. Distillable into vivid architectural pigments.',
    iconName: 'Sparkles',
    color: '#ec4899',
    rarity: 'common',
    maxStack: 99,
  },
  sweet_nectar: {
    id: 'sweet_nectar',
    name: 'Sweet Nectar',
    category: 'raw',
    description: 'High-sugar floral syrup. Irresistible bait used to tame gentle critters like Soft-Puffs.',
    iconName: 'Sun',
    color: '#fbbf24',
    rarity: 'uncommon',
    maxStack: 99,
  },
  soft_fiber: {
    id: 'soft_fiber',
    name: 'Ribbon Fiber',
    category: 'raw',
    description: 'Tough, supple fibers harvested from Ribbon-Moss. Woven into flexible conduits and floors.',
    iconName: 'Layers',
    color: '#2dd4bf',
    rarity: 'common',
    maxStack: 99,
  },
  dew_essence: {
    id: 'dew_essence',
    name: 'Dew Essence',
    category: 'raw',
    description: 'Condensation gathered in Bell-Bloom cups, charged with atmospheric bioluminescence.',
    iconName: 'CloudRain',
    color: '#38bdf8',
    rarity: 'common',
    maxStack: 99,
  },
  bio_pellet: {
    id: 'bio_pellet',
    name: 'Bio-Pellets',
    category: 'raw',
    description: 'Nutrient-dense pellets excreted by tamed Soft-Puffs. Crucial for high-grade Growth Fertilizer.',
    iconName: 'CircleDot',
    color: '#10b981',
    rarity: 'uncommon',
    maxStack: 99,
  },
  carapace_scale: {
    id: 'carapace_scale',
    name: 'Carapace Scale',
    category: 'raw',
    description: 'Naturally shed armor plate from Chitin-Stalkers. Provides immense structural rigidity.',
    iconName: 'Shield',
    color: '#8b5cf6',
    rarity: 'rare',
    maxStack: 99,
  },
  prismatic_core: {
    id: 'prismatic_core',
    name: 'Prismatic Core',
    category: 'raw',
    description: 'Crystallized bio-luminescent node gathered from rare alien flora blooms.',
    iconName: 'Gem',
    color: '#06b6d4',
    rarity: 'prismatic',
    maxStack: 99,
  },
  basic_compost: {
    id: 'basic_compost',
    name: 'Organic Compost',
    category: 'raw',
    description: 'Decomposed botanical matter rich in fungal mycelium.',
    iconName: 'Sprout',
    color: '#78716c',
    rarity: 'common',
    maxStack: 99,
  },

  // Cultivation Seeds
  seed_lantern_fern: {
    id: 'seed_lantern_fern',
    name: 'Lantern-Fern Spore',
    category: 'seed',
    description: 'Grow glowing fern stalks that radiate neon bioluminescence across your outpost.',
    iconName: 'Zap',
    color: '#06b6d4',
    rarity: 'common',
    maxStack: 50,
  },
  seed_sap_weaver: {
    id: 'seed_sap_weaver',
    name: 'Sap-Weaver Seed',
    category: 'seed',
    description: 'Cultivates a bulbous resin-producing plant. Yields regular supplies of sticky resin sap.',
    iconName: 'Droplets',
    color: '#f59e0b',
    rarity: 'uncommon',
    maxStack: 50,
  },
  seed_petal_mill: {
    id: 'seed_petal_mill',
    name: 'Petal-Mill Seed',
    category: 'seed',
    description: 'Cultivates rotating pinwheel petals producing fragrant sweet nectar and vibrant pigments.',
    iconName: 'Flower',
    color: '#ec4899',
    rarity: 'uncommon',
    maxStack: 50,
  },
  seed_snap_trap: {
    id: 'seed_snap_trap',
    name: 'Snap-Trap Bulb',
    category: 'seed',
    description: 'Carnivorous flora bulb. When domesticated, snaps at intruding threats.',
    iconName: 'AlertTriangle',
    color: '#ef4444',
    rarity: 'rare',
    maxStack: 30,
  },
  seed_bell_bloom: {
    id: 'seed_bell_bloom',
    name: 'Bell-Bloom Spore',
    category: 'seed',
    description: 'Cultivates musical swaying bells that distill morning dew and soft bio-fibers.',
    iconName: 'Bell',
    color: '#818cf8',
    rarity: 'common',
    maxStack: 50,
  },

  // Fertilizers
  growth_fertilizer: {
    id: 'growth_fertilizer',
    name: 'Growth Fertilizer',
    category: 'fertilizer',
    description: 'Compound of Compost and Bio-Pellets. Triples flora maturation speed without soil depletion.',
    iconName: 'Flame',
    color: '#10b981',
    rarity: 'uncommon',
    maxStack: 50,
  },
  yield_fertilizer: {
    id: 'yield_fertilizer',
    name: 'Yield Fertilizer',
    category: 'fertilizer',
    description: 'Refined from Animal Secretions & Resin Sap. Boosts harvest yield and sparks prismatic variants.',
    iconName: 'Sparkle',
    color: '#a855f7',
    rarity: 'rare',
    maxStack: 50,
  },

  // Living Bio-Structures
  root_tile_floor: {
    id: 'root_tile_floor',
    name: 'Root-Tile Floor',
    category: 'structure',
    description: 'Interlocking woven-wood base tile. Provides smooth walking speed and foundation.',
    iconName: 'Grid',
    color: '#0d9488',
    rarity: 'common',
    maxStack: 99,
  },
  chitin_glass_wall: {
    id: 'chitin_glass_wall',
    name: 'Chitin-Glass Wall',
    category: 'structure',
    description: 'Semi-translucent porcelain wall reinforced with chitin fibers. Filters ambient light.',
    iconName: 'Square',
    color: '#38bdf8',
    rarity: 'common',
    maxStack: 99,
  },
  iris_slit_door: {
    id: 'iris_slit_door',
    name: 'Iris-Slit Proximity Door',
    category: 'structure',
    description: 'Living sphincter iris doorway. Unweaves automatically when authorized players approach!',
    iconName: 'Maximize2',
    color: '#ec4899',
    rarity: 'uncommon',
    maxStack: 50,
  },
  lantern_fern_post: {
    id: 'lantern_fern_post',
    name: 'Lantern-Fern Lamp',
    category: 'structure',
    description: 'Living lamppost rooted in place, casting vibrant bioluminescent light.',
    iconName: 'Lightbulb',
    color: '#22d3ee',
    rarity: 'common',
    maxStack: 50,
  },
  spore_canopy: {
    id: 'spore_canopy',
    name: 'Spore-Canopy Ceiling',
    category: 'structure',
    description: 'Domed organic ceiling that filters environmental dust and condenses ambient dew.',
    iconName: 'Umbrella',
    color: '#8b5cf6',
    rarity: 'uncommon',
    maxStack: 50,
  },
  bio_forge_station: {
    id: 'bio_forge_station',
    name: 'Bio-Forge Workstation',
    category: 'structure',
    description: 'Advanced biological synthesis terminal for synthesizing seeds, fertilizers, and composites.',
    iconName: 'Cpu',
    color: '#06b6d4',
    rarity: 'rare',
    maxStack: 10,
  },
  tamed_snap_trap_turret: {
    id: 'tamed_snap_trap_turret',
    name: 'Tamed Snap-Trap Turret',
    category: 'structure',
    description: 'Stationary bio-defense sentry. Shoots organic thorns at wild predators.',
    iconName: 'Target',
    color: '#ef4444',
    rarity: 'rare',
    maxStack: 20,
  },
  cultivation_mound: {
    id: 'cultivation_mound',
    name: 'Cultivation Mound',
    category: 'structure',
    description: 'Enriched soil mound engineered for domestic flora cultivation and fertilizer application.',
    iconName: 'Circle',
    color: '#4ade80',
    rarity: 'common',
    maxStack: 99,
  },
};

export const RECIPES: CraftingRecipe[] = [
  // Seeds
  {
    id: 'craft_seed_lantern_fern',
    outputId: 'seed_lantern_fern',
    outputCount: 2,
    name: 'Lantern-Fern Spores',
    description: 'Synthesize glowing fern spores from soft fibers and dew essence.',
    category: 'seeds',
    ingredients: [
      { id: 'soft_fiber', count: 2 },
      { id: 'dew_essence', count: 1 },
    ],
    craftTimeMs: 1200,
  },
  {
    id: 'craft_seed_sap_weaver',
    outputId: 'seed_sap_weaver',
    outputCount: 2,
    name: 'Sap-Weaver Seed',
    description: 'Congeal resin sap into viable cultivator seeds.',
    category: 'seeds',
    ingredients: [
      { id: 'resin_sap', count: 3 },
      { id: 'basic_compost', count: 1 },
    ],
    craftTimeMs: 1500,
  },
  {
    id: 'craft_seed_petal_mill',
    outputId: 'seed_petal_mill',
    outputCount: 2,
    name: 'Petal-Mill Seed',
    description: 'Fuse vibrant petals and sweet nectar into pinwheel floral seeds.',
    category: 'seeds',
    ingredients: [
      { id: 'vibrant_petal', count: 3 },
      { id: 'sweet_nectar', count: 1 },
    ],
    craftTimeMs: 1500,
  },
  {
    id: 'craft_seed_snap_trap',
    outputId: 'seed_snap_trap',
    outputCount: 1,
    name: 'Snap-Trap Bulb',
    description: 'Bio-engineer a domestic carnivorous snap-trap bulb using carapace scales and sap.',
    category: 'seeds',
    ingredients: [
      { id: 'carapace_scale', count: 2 },
      { id: 'resin_sap', count: 2 },
      { id: 'sweet_nectar', count: 2 },
    ],
    craftTimeMs: 2500,
  },

  // Fertilizers
  {
    id: 'craft_growth_fertilizer',
    outputId: 'growth_fertilizer',
    outputCount: 2,
    name: 'Growth Fertilizer',
    description: 'Mix organic compost and critter Bio-Pellets to accelerate plant maturation.',
    category: 'fertilizers',
    ingredients: [
      { id: 'basic_compost', count: 2 },
      { id: 'bio_pellet', count: 2 },
    ],
    craftTimeMs: 1500,
  },
  {
    id: 'craft_yield_fertilizer',
    outputId: 'yield_fertilizer',
    outputCount: 2,
    name: 'Yield Fertilizer',
    description: 'Synthesize specialized fertilizer from resin sap and carapace secretions to boost harvest yield.',
    category: 'fertilizers',
    ingredients: [
      { id: 'resin_sap', count: 2 },
      { id: 'carapace_scale', count: 1 },
      { id: 'dew_essence', count: 2 },
    ],
    craftTimeMs: 2000,
  },

  // Composites & Building Seed-Nodes
  {
    id: 'craft_root_tile',
    outputId: 'root_tile_floor',
    outputCount: 4,
    name: 'Root-Tile Floor (x4)',
    description: 'Interlock woven fibers and cellulose into a sturdy bio-floor node.',
    category: 'composites',
    ingredients: [
      { id: 'soft_fiber', count: 2 },
      { id: 'basic_compost', count: 1 },
    ],
    craftTimeMs: 1000,
  },
  {
    id: 'craft_chitin_wall',
    outputId: 'chitin_glass_wall',
    outputCount: 2,
    name: 'Chitin-Glass Wall (x2)',
    description: 'Form translucent porcelain wall panels bonded with flex resin.',
    category: 'composites',
    ingredients: [
      { id: 'resin_sap', count: 2 },
      { id: 'dew_essence', count: 2 },
    ],
    craftTimeMs: 1200,
  },
  {
    id: 'craft_iris_door',
    outputId: 'iris_slit_door',
    outputCount: 1,
    name: 'Iris-Slit Proximity Door',
    description: 'Living wall section engineered with a sphincter iris that unweaves upon proximity.',
    category: 'composites',
    ingredients: [
      { id: 'resin_sap', count: 3 },
      { id: 'vibrant_petal', count: 2 },
      { id: 'soft_fiber', count: 2 },
    ],
    craftTimeMs: 2000,
  },
  {
    id: 'craft_lantern_post',
    outputId: 'lantern_fern_post',
    outputCount: 1,
    name: 'Lantern-Fern Lamp',
    description: 'Rooted bioluminescent pillar providing ambient light.',
    category: 'composites',
    ingredients: [
      { id: 'soft_fiber', count: 2 },
      { id: 'dew_essence', count: 2 },
      { id: 'vibrant_petal', count: 1 },
    ],
    craftTimeMs: 1200,
  },
  {
    id: 'craft_cultivation_mound',
    outputId: 'cultivation_mound',
    outputCount: 2,
    name: 'Cultivation Mound (x2)',
    description: 'Enriched soil mound engineered for planting domestic flora.',
    category: 'composites',
    ingredients: [
      { id: 'basic_compost', count: 2 },
      { id: 'soft_fiber', count: 1 },
    ],
    craftTimeMs: 1000,
  },
  {
    id: 'craft_spore_canopy',
    outputId: 'spore_canopy',
    outputCount: 1,
    name: 'Spore-Canopy Ceiling',
    description: 'Domed organic shelter that shields the interior and harvests rainwater.',
    category: 'composites',
    ingredients: [
      { id: 'soft_fiber', count: 4 },
      { id: 'resin_sap', count: 2 },
      { id: 'dew_essence', count: 2 },
    ],
    craftTimeMs: 2000,
  },

  // Defenses
  {
    id: 'craft_snap_trap_turret',
    outputId: 'tamed_snap_trap_turret',
    outputCount: 1,
    name: 'Snap-Trap Defense Sentry',
    description: 'Stationary defensive bio-turret that targets and subdues wild hostile predators.',
    category: 'defenses',
    ingredients: [
      { id: 'seed_snap_trap', count: 1 },
      { id: 'carapace_scale', count: 2 },
      { id: 'resin_sap', count: 3 },
    ],
    craftTimeMs: 3000,
  },
];

export const INITIAL_CODEX: CodexEntry[] = [
  {
    species: 'lantern_fern',
    name: 'Prismatic Lantern-Fern',
    type: 'flora',
    discovered: true,
    scannedCount: 1,
    description: 'Dynamic photosynthetic flora capable of emitting high-frequency cool cyan and teal bioluminescence. Recharges at dusk.',
    byproducts: ['Soft Fiber', 'Dew Essence'],
    tamingOrCraftNotes: 'Harvest non-lethally by gently pruning lateral glowing bulbs. Can be cultivated in garden mounds.',
    biome: 'Violet Cradle & Amber Thicket',
    iconColor: '#06b6d4',
  },
  {
    species: 'sap_weaver',
    name: 'Sap-Weaver',
    type: 'flora',
    discovered: true,
    scannedCount: 1,
    description: 'Amber bulbous organism that excretes viscous, sticky resins used as bonding agent for bio-composite building.',
    byproducts: ['Resin Sap'],
    tamingOrCraftNotes: 'Extract sap reservoir using Harvest Glove. Enjoys growth fertilizer for rapid replenishing.',
    biome: 'Amber Thicket',
    iconColor: '#f59e0b',
  },
  {
    species: 'petal_mill',
    name: 'Petal-Mill',
    type: 'flora',
    discovered: false,
    scannedCount: 0,
    description: 'Symmetrical kinetic blossom with pinwheel petals that rotate in thermal updrafts, aerating sweet nectar.',
    byproducts: ['Vibrant Petals', 'Sweet Nectar'],
    tamingOrCraftNotes: 'Produces primary bait for fauna domestication. Yield fertilizer triggers prismatic rainbow blooms.',
    biome: 'Turquoise Glade',
    iconColor: '#ec4899',
  },
  {
    species: 'mouth_vine',
    name: 'Mouth-Vine',
    type: 'flora',
    discovered: false,
    scannedCount: 0,
    description: 'Semi-carnivorous creeping tendrils that reflexively snap toward fast movement. Prone to constriction.',
    byproducts: ['Tough Fibers', 'Digestive Fluid'],
    tamingOrCraftNotes: 'Pacify by feeding Sweet Nectar before harvesting or pruning back.',
    biome: 'Prismatic Verge',
    iconColor: '#84cc16',
  },
  {
    species: 'snap_trap',
    name: 'Chittering Snap-Trap',
    type: 'flora',
    discovered: false,
    scannedCount: 0,
    description: 'Large, noisy carnivorous bloom with interlocking porcelain-toothed jaws. Territorial in the wild.',
    byproducts: ['Acidic Resins', 'Hardened Thorns'],
    tamingOrCraftNotes: 'Can be bio-forged into stationary base defenses to protect crops from wild predators.',
    biome: 'Prismatic Verge',
    iconColor: '#ef4444',
  },
  {
    species: 'soft_puff',
    name: 'Soft-Puff Critter',
    type: 'fauna',
    discovered: true,
    scannedCount: 1,
    description: 'Spherical, docile creature covered in luminescent fur. Forages on organic detritus and cleans base perimeters.',
    byproducts: ['Bio-Pellets (High-Grade Fertilizer)'],
    tamingOrCraftNotes: 'Tame by offering Sweet Nectar with the Taming Lure tool. Tamed variants wander nearby base and drop fertilizer.',
    biome: 'Violet Cradle & Turquoise Glade',
    iconColor: '#2dd4bf',
  },
  {
    species: 'burrow_mouse',
    name: 'Burrow-Mouse',
    type: 'fauna',
    discovered: false,
    scannedCount: 0,
    description: 'Agile rodent-like creature with crystalline whiskers. Digs up dormant spores and roots.',
    byproducts: ['Bio-Pellets', 'Compost Nodules'],
    tamingOrCraftNotes: 'Approaches curious explorers carrying Sweet Nectar or Dew Essence.',
    biome: 'Amber Thicket',
    iconColor: '#f97316',
  },
  {
    species: 'chitin_stalker',
    name: 'Chitin-Stalker',
    type: 'fauna',
    discovered: false,
    scannedCount: 0,
    description: 'Sleek quad-legged predator clad in iridescent porcelain-scale carapace. Highly territorial.',
    byproducts: ['Reinforced Carapace Scale'],
    tamingOrCraftNotes: 'Subdue with food distraction or pacifying lure. Once tamed, patrols base grounds and repels hostile threats.',
    biome: 'Prismatic Verge',
    iconColor: '#a855f7',
  },
  {
    species: 'scale_bear',
    name: 'Scale-Bear Guardian',
    type: 'fauna',
    discovered: false,
    scannedCount: 0,
    description: 'Massive apex herbivore encased in heavy bio-plating. Gentle unless provoked.',
    byproducts: ['Heavy Chitin Plates', 'Pure Animal Secretions'],
    tamingOrCraftNotes: 'Requires substantial offering of Sweet Nectar and Petals.',
    biome: 'Deep Glade',
    iconColor: '#6366f1',
  },
  {
    species: 'iris_slit_door',
    name: 'Iris-Slit Proximity Door',
    type: 'composite',
    discovered: true,
    scannedCount: 1,
    description: 'Living sphincter iris doorway woven from flex-resins and spore-hinges. Automatically dilates when players approach.',
    byproducts: ['100% Recyclable with Solvent Sprayer'],
    tamingOrCraftNotes: 'Craft at Bio-Forge Workstation. Recycles into raw seed-nodes on deconstruction.',
    biome: 'Base Architecture',
    iconColor: '#ec4899',
  },
  {
    species: 'root_tile_floor',
    name: 'Root-Tile Foundation',
    type: 'composite',
    discovered: true,
    scannedCount: 1,
    description: 'Interlocking bio-cellulose floor grown directly on soil to provide steady footing and suppress hazardous weeds.',
    byproducts: ['100% Recyclable with Solvent Sprayer'],
    tamingOrCraftNotes: 'Fast growth rate. Eliminates terrain speed penalties.',
    biome: 'Base Architecture',
    iconColor: '#0d9488',
  },
  {
    species: 'chitin_glass_wall',
    name: 'Chitin-Glass Wall',
    type: 'composite',
    discovered: true,
    scannedCount: 1,
    description: 'Translucent, resilient structural partition letting natural bioluminescent sunlight filter through.',
    byproducts: ['100% Recyclable with Solvent Sprayer'],
    tamingOrCraftNotes: 'Withstands creature attacks and environmental dust.',
    biome: 'Base Architecture',
    iconColor: '#38bdf8',
  },
];

export const INITIAL_INVENTORY = [
  { id: 'resin_sap', count: 12 },
  { id: 'vibrant_petal', count: 10 },
  { id: 'sweet_nectar', count: 8 },
  { id: 'soft_fiber', count: 16 },
  { id: 'dew_essence', count: 8 },
  { id: 'basic_compost', count: 12 },
  { id: 'bio_pellet', count: 6 },
  { id: 'carapace_scale', count: 4 },
  { id: 'growth_fertilizer', count: 4 },
  { id: 'yield_fertilizer', count: 2 },
  { id: 'seed_lantern_fern', count: 5 },
  { id: 'seed_sap_weaver', count: 4 },
  { id: 'seed_petal_mill', count: 4 },
  { id: 'root_tile_floor', count: 16 },
  { id: 'chitin_glass_wall', count: 8 },
  { id: 'iris_slit_door', count: 2 },
  { id: 'cultivation_mound', count: 6 },
  { id: 'lantern_fern_post', count: 4 },
  { id: 'bio_forge_station', count: 1 },
] as const;

export const BIOMES = [
  {
    name: 'Violet Cradle',
    description: 'Deep violet soils rich in mycelium, fluorescent mushrooms, and tranquil Soft-Puffs.',
    groundColor: 0x221330,
    ambientLightColor: 0x9370db,
    fogColor: 0x140e24,
    primaryTone: 'Violet',
    bounds: { minX: -50, maxX: 0, minZ: -50, maxZ: 0 },
  },
  {
    name: 'Turquoise Glade',
    description: 'Lush cyan and teal moss carpeted with resonant Bell-Blooms and dancing dew drops.',
    groundColor: 0x0f2b2b,
    ambientLightColor: 0x2dd4bf,
    fogColor: 0x071e22,
    primaryTone: 'Turquoise',
    bounds: { minX: 0, maxX: 50, minZ: -50, maxZ: 0 },
  },
  {
    name: 'Amber Thicket',
    description: 'Golden crystalline sap pools, rotating Petal-Mills, and burrowing wildlife.',
    groundColor: 0x2a1c0d,
    ambientLightColor: 0xf59e0b,
    fogColor: 0x1c1308,
    primaryTone: 'Amber',
    bounds: { minX: -50, maxX: 0, minZ: 0, maxZ: 50 },
  },
  {
    name: 'Prismatic Verge',
    description: 'Challenging frontier inhabited by territorial Chitin-Stalkers and carnivorous Snap-Traps.',
    groundColor: 0x1b1933,
    ambientLightColor: 0x818cf8,
    fogColor: 0x0d0b21,
    primaryTone: 'Prismatic',
    bounds: { minX: 0, maxX: 50, minZ: 0, maxZ: 50 },
  },
];
